runtime: python37
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app
  login: admin

libraries:
- name: ssl
  version: latest

env_variables:
  CONSUMER_KEY: '34jeLWTsriGQERTCJjZwkgV84'
  CONSUMER_SECRET: 'EJnXeiTCJsXMZR5nvdr7gkppGF5lF6CG1kK3VDur0FuPGEEWrk'
  ACCESS_TOKEN: '142500263-hm45GZiSwvvnYsfvVDmO0FStkK7JAR85EBTfkT2s'
  ACCESS_TOKEN_SECRET: 'XXqtybDcRKzrpxpkPpJBGd0JVNr9O5GW8F7JQUK0QDKdv'
  PROJECT: 'servinf-geomark-social-prod'
  DATASET: 'Twittero'
  BUCKET: 'tts_sample1'
  TEMPLATE_NAME: 'servinf-geomark-social-prod-twproc_tmpl'
